### ISSUE TITLE
Recommanded approach to register a new menu?

### ISSUE THREAD

**Issue by nasirkhan** [hexadog/laravel-menus-manager#15]
What is the recommended place to call the `$menu = Menus::register('main');` to create a new menu? 

If I want to create a frontend menu that will be open to all the visitors? should I create a new service provider or use some middleware or something else?

**Comment by gaetan-hexadog** [comment]
Hi @nasirkhan ,

You can put this code into your `AppServiceProvider` within the `boot` method.

```php
<?php

namespace App\Providers;

use Hexadog\MenusManager\Facades\MenusManager;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot()
    {
        $this->buildBackendMenu();
        $this->buildFrontendMenu();
    }

    protected function buildBackendMenu()
    {
        $backendMenu = MenusManager::register('backend.main');

        // Define Backend Menu
    }

    protected function buildFrontendMenu()
    {
        $frontendMenu = MenusManager::register('tenant.main');

        // Define Frontend menu
        /* $frontendMenu->route(['dashboard'], __('Dashboard'))
            ->icon('tabler-dashboard')
            ->order(-1); */
    }
}
```

**Comment by nasirkhan** [comment]
The following code does not work, as auth is not available in the AppServiceProvider. does it work for you? I want to check if the current user is have access to a specific menu item

```
$menu->route('post.create', __('New Post'))->if(Auth()->check())->if(Auth()->user()->can('create.post'));
```

**Comment by gaetan-hexadog** [comment]
Yes, you can use `Auth` in a service provider. I think you have a typo in your code. It's supposed to be `auth()` in lowercase ;-)

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        dd(Auth::check());
    }
}
```

**Comment by nasirkhan** [comment]
Thank you for your reply.

I tried this on a fresh Laravel 10 project and `dd(Auth::check());` is showing `false` for both logged-in users and guests.

I was searching some related issue in the internet and many of these mentioned that session starts in Middlewire and I will not be able to access Auth from a service provider (https://stackoverflow.com/questions/35275296/laravel-5-1-authcheck-return-false-in-serviceprovider). some posts do suggested code like you mentioned above. 

to get access to the Auth, do you need to change anything in your application? do you have any recent built project where can i see it working?

**Comment by gaetan-hexadog** [comment]
Have you tried to use a callback to check the auth ?

```php
$menu->route('post.create', __('New Post'))->if(fn () => auth()->check());
```

**Comment by nasirkhan** [comment]
Following code works

```
$menu->route('profile.show', __('Profile'))->if(Auth()->check());
```

but this does not

```
$menu->route('post.create', __('New Post'))->if(Auth()->check())->if(Auth()->user()->can('view_backend'));
```

with the following error

```
Call to a member function can() on null
```

I am testing this package with this project: https://github.com/nasirkhan/laravel-starter/blob/menu/app/Providers/AppServiceProvider.php

**Comment by gaetan-hexadog** [comment]
Thansk for the reop.

Did you tried using a callback as suggested in my previous answer ?

```php
$menu->route('post.create', __('New Post'))->if(fn () => Auth()->check() && Auth()->user()->can('view_backend'));
```

**Comment by nasirkhan** [comment]
> Thansk for the reop.
> 
> Did you tried using a callback as suggested in my previous answer ?
> 
> ```
> $menu->route('post.create', __('New Post'))->if(() => Auth()->check() && Auth()->user()->can('view_backend'));
> ```

This does not work. I mentioned it above that without the `can` it works.

**Comment by gaetan-hexadog** [comment]
Hi,

As previously suggested: use a callback to check authorization. This way the check does not run during the application boot process but when menu is retreived and displayed.

The following code works in your project:

```php
$menu->route('post.create', __('New Post'))->if(fn () => Auth()->check() && Auth()->user()->can('create.post'));
```

**Notice the `fn() =>` callback syntax used.** (I used an [arrow function](https://www.php.net/manual/en/functions.arrow.php) but you can use a classic one if prefered)

**Comment by nasirkhan** [comment]
This is working as expected. Thank you for your support.

> ```
> $menu->route('post.create', __('New Post'))->if(fn () => Auth()->check() && Auth()->user()->can('create.post'));
> ```

I was following the doc and the code of the doc does not work. It needed to be updated.

**Comment by gaetan-hexadog** [comment]
Thanks for your feedback.

I have fixed the documentation.

**Comment by nasirkhan** [comment]
localization is not working, in the following code. Is it working for you ? 

```
$menu->route('post.create', __('New Post'))->if(fn () => Auth()->check() && Auth()->user()->can('create.post'));
```

**Comment by gaetan-hexadog** [comment]
Hi @nasirkhan ,

please see #16 and the `v1.2.3` release fixing this issue.

thanks again for your feedbacks
