### ISSUE TITLE
Localization is not working on menu declaration

### ISSUE THREAD

**Issue by gaetan-hexadog** [hexadog/laravel-menus-manager#16]
Open dedicated issue from #15 by @nasirkhan

> localization is not working, in the following code. Is it working for you ?
> 
> $menu->route('post.create', __('New Post'))->if(fn () => Auth()->check() && Auth()->user()->can('create.post'));
>

**Comment by gaetan-hexadog** [comment]
Hi @nasirkhan,

the `v1.2.3` has been released to fix this issue.
Menu item title can now be declared using a Closure (for localization purpose for example)

```php
$menu->route('post.create', fn () => __('New Post'))->if(fn () => Auth()->check() && Auth()->user()->can('create.post'));
```

**Comment by nasirkhan** [comment]
Thanks for your support. It is working now. 

Submitted a PR to update the doc as well.
