### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by nasirkhan** [hexadog/laravel-menus-manager#18]
Hi, 
I was planning to use this extension on my project, but unfortunately, it does not support Laravel 11. Are you working on it? how long it may take to publish the new version?

**Comment by gaetan-hexadog** [comment]
Hi @nasirkhan ,

I'll try to work on it this week to release an update with Laravel 11 support.

**Comment by nasirkhan** [comment]
thanks

--
*Nasir Khan Saikat*
nasirkhn.com
